export const initialProducts = [
  {
    id: 1,
    name: "Polera Metallica - Ride the Lightning",
    category: "Poleras",
    price: 24990,
    size: "M",
    stock: 14,
    location: "Pasillo 3 - Estante B",
    description: "Polera 100% algodón con estampado del álbum Ride the Lightning de Metallica.",
    image:
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 2,
    name: "Chaqueta de Cuero Metalhead",
    category: "Chaquetas",
    price: 89990,
    size: "L",
    stock: 6,
    location: "Pasillo 1 - Estante A",
    description: "Chaqueta de cuero genuino estilo metalero con cierres metálicos y forro interior.",
    image:
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 3,
    name: "Polerón Iron Maiden",
    category: "Polerones",
    price: 44990,
    size: "XL",
    stock: 9,
    location: "Pasillo 2 - Estante C",
    description: "Polerón con capucha y el icónico logo de Iron Maiden bordado en el pecho.",
    image:
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 4,
    name: "Polera Black Sabbath - Paranoid",
    category: "Poleras",
    price: 27990,
    size: "L",
    stock: 11,
    location: "Pasillo 3 - Estante D",
    description: "Polera negra edición Paranoid de Black Sabbath, corte clásico unisex.",
    image:
      "https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 5,
    name: "Polerón Slayer - Reign in Blood",
    category: "Polerones",
    price: 46990,
    size: "M",
    stock: 5,
    location: "Pasillo 2 - Estante D",
    description: "Polerón con gráfico de Reign in Blood de Slayer, suave y resistente.",
    image:
      "https://images.unsplash.com/photo-1578681994506-b8f463449011?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 7,
    name: "Polera One Piece - Straw Hat Pirates",
    category: "Anime",
    price: 23990,
    size: "M",
    stock: 12,
    location: "Pasillo 4 - Estante A",
    description: "Polera de One Piece con el símbolo de los Mugiwara en el pecho.",
    image: "https://placehold.co/800x1000/9333ea/FFFFFF?text=One+Piece+Merch",
  },
  {
    id: 8,
    name: "Polera Demon Slayer - Nichirin",
    category: "Anime",
    price: 25990,
    size: "L",
    stock: 8,
    location: "Pasillo 4 - Estante B",
    description: "Polera de Kimetsu no Yaiba inspirada en las espadas Nichirin.",
    image: "https://placehold.co/800x1000/DC2626/FFFFFF?text=Demon+Slayer+Merch",
  },
  {
    id: 9,
    name: "Polera Attack on Titan - Scout Regiment",
    category: "Anime",
    price: 22990,
    size: "XL",
    stock: 3,
    location: "Pasillo 4 - Estante C",
    description: "Polera del Cuerpo de Exploración de Attack on Titan con el emblema alado.",
    image: "https://placehold.co/800x1000/1E40AF/FFFFFF?text=Scout+Regiment",
  },
  {
    id: 10,
    name: "Beanie Negro con Cuervo - Accesorio",
    category: "Accesorios",
    price: 12990,
    size: "Único",
    stock: 20,
    location: "Pasillo 5 - Estante A",
    description: "Gorro beanie de invierno con bordado de cuervo, talla única ajustable.",
    image:
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 11,
    name: "Pulsera de Cuero con Colgante Skull",
    category: "Accesorios",
    price: 8990,
    size: "Único",
    stock: 15,
    location: "Pasillo 5 - Estante B",
    description: "Pulsera de cuero trenzado con colgante de calavera en metal envejecido.",
    image:
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 12,
    name: "Gorro de Lana Metallica - Accesorio",
    category: "Accesorios",
    price: 15990,
    size: "Único",
    stock: 2,
    location: "Pasillo 5 - Estante C",
    description: "Gorro de lana estilo trucker con logo de Metallica bordado al frente.",
    image:
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
  },
];

export const adminUsers = [
  {
    id: 1,
    name: "Elias Figueroa",
    username: "elias",
    password: "1234",
    email: "elias@rockstar.cl",
    role: "Administrador",
  },
  {
    id: 2,
    name: "Jorge Pina",
    username: "Jp",
    password: "1234",
    email: "jorge.pina@rockstar.cl",
    role: "Administrador",
  },
  {
    id: 3,
    name: "Exequiel Tapia",
    username: "Exe",
    password: "1234",
    email: "exequiel.tapia@rockstar.cl",
    role: "Administrador",
  },
];

export const money = (value) =>
  new Intl.NumberFormat("es-CL", {
    style: "currency",
    currency: "CLP",
    maximumFractionDigits: 0,
  }).format(value);
